source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'sqlite3', '~> 1.3.6'
gem 'rack', '1.6.0'
gem 'devise', '3.5.0'
gem 'cancancan', '~> 1.10'

gem 'nokogiri', '1.6.8'
gem 'loofah', '2.0.3'
gem 'rack-cors', '0.4.0'
gem 'omniauth', '1.3.1'
gem 'omniauth-oauth2', '1.4.0'
gem 'rails-html-sanitizer', '1.0.3'

gem 'jquery-rails'
gem 'turbolinks'
gem 'coffee-rails'
gem 'sass-rails'
gem 'uglifier'
gem 'therubyracer'

gem 'jquery-rails'
gem 'sass-rails'

gem 'activesupport', '4.2.0'
gem 'activerecord', '4.2.0'

group :development, :test do
  gem 'byebug', platform: :mri
end

group :development do
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'pry-rails'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :production do
  gem 'rails_12factor'
  gem 'newrelic_rpm'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'paperclip', '4.3.0'
